# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Minhoca
tagline:          'What digital future do we want to build?'
description:      'A blog about digital society and preparing for digital life in the second quarter of the 21st century.'
# url:              http://hyde.getpoole.com
baseurl:          /

# author:
#   name:           'Mark Otto'
#   url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
